spring:
  application:
    name: spring-alibaba-demo
  ai:
    dashscope:
      api-key: sk-3696800b571e4f2ab6dbc100bf19ccb0
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v3